services:
  - type: web
    name: brigade-chatbot-api
    env: python
    region: oregon
    rootDir: backend
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install --no-deps pixeltable==0.2.30
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --loop asyncio
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: TAVILY_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: LLM_MODEL
        value: gpt-4
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIXELTABLE_DB_URL
        sync: false

