services:
  - type: web
    name: brigade-chatbot-api
    runtime: docker
    region: oregon
    rootDir: backend
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: TAVILY_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-small
      - key: LLM_MODEL
        value: gpt-4
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PIXELTABLE_DB_URL
        sync: false

